apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-gop-eng
  namespace: ml-prd
spec:
  maxReplicas: 3  # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gop-eng
  targetCPUUtilizationPercentage: 80 # target CPU utilization
